### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by sergei-mironov** [klevin92/covid19_moscow_cases#2]
Hi. I found your repo on a GitHub by 'moscow covid' keywords. I attempt to maintain a repository on the similar topic:

https://github.com/grwlf/COVID-19_plus_Russia

In this repo I'm trying to update CSSE repo with Moscow/Spb data (please see the readme). I'd be happy to join attempts in monitoring per-city covid in Russia.

**Comment by klevin92** [comment]
Приветствую!

Да, можно попробовать. Я смотрел их репозиторий когда начинал - там не было разделения на города. Плюс я не разобрался как получить графики для конкретной страны кроме Китая/США/etc. Есть какой-то конкретный план действий?

Плюс есть такой [проект](https://github.com/AaronWard/covid-19-analysis).
Правда я не смог завести его на винде - он упорно не репортил ничего и не выдавал внятных ошибок.

**Comment by sergei-mironov** [comment]
Спасибо, посмотрю и добавлю в список ссылок. Я сделал ишью где можно обсуждать тех.детали. Готов поддержать нужный API https://github.com/grwlf/COVID-19_plus_Russia/issues/1
